/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuralnetwork;

import java.awt.Label;
import java.util.ArrayList;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Richard Karsan BIF 77353 && Otaalo John Chrispine BIF 73758
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOne = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTwo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableThree = new javax.swing.JTable();
        verifyButton = new javax.swing.JButton();
        submitButtonTwo = new javax.swing.JButton();
        submitButtonOne = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tableOneResultLabel = new javax.swing.JLabel();
        tableTwoResultLabel = new javax.swing.JLabel();
        finalTableResultLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableOne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableOne.setTableHeader(null);
        tableOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOne);

        tableTwo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableTwo.setTableHeader(null);
        tableTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTwoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTwo);

        tableThree.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."},
                {".", ".", ".", ".", ".", "."}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableThree.setTableHeader(null);
        tableThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThreeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableThree);

        verifyButton.setText("Verify Final");
        verifyButton.setActionCommand("verifyFinal");
        verifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verifyButtonMouseClicked(evt);
            }
        });

        submitButtonTwo.setText("Submit Two");
        submitButtonTwo.setActionCommand("submitTwo");
        submitButtonTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonTwoMouseClicked(evt);
            }
        });

        submitButtonOne.setText("Submit One");
        submitButtonOne.setActionCommand("submitOne");
        submitButtonOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonOneMouseClicked(evt);
            }
        });

        jLabel1.setText("Table One: ");

        jLabel2.setText("Table Two: ");

        jLabel3.setText("Final Value: ");

        tableOneResultLabel.setText("0");

        tableTwoResultLabel.setText("0");

        finalTableResultLabel.setText("0");

        jLabel4.setText("Richard Seth Karsan 77353");

        jLabel5.setText("Otaalo John Chrispine 73758");

        jLabel6.setText("BIF Artificial Intelligence: Neural Networks Assignment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitButtonTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tableTwoResultLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(finalTableResultLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tableOneResultLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitButtonOne)
                            .addComponent(submitButtonTwo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(verifyButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tableOneResultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tableTwoResultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(finalTableResultLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOneMouseClicked
        // TODO add your handling code here:
        //On click for first table
        int row = tableOne.getSelectedRow();
        int column = tableOne.getSelectedColumn();
        
        changeCellValue(tableOne, row, column);
    }//GEN-LAST:event_tableOneMouseClicked

    private void tableTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTwoMouseClicked
        // TODO add your handling code here:
        //On click for second table
        int row = tableTwo.getSelectedRow();
        int column = tableTwo.getSelectedColumn();
        
        changeCellValue(tableTwo, row, column);
    }//GEN-LAST:event_tableTwoMouseClicked

    private void tableThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThreeMouseClicked
        // TODO add your handling code here:
        //On click for third table
        int row = tableThree.getSelectedRow();
        int column = tableThree.getSelectedColumn();
        
        changeCellValue(tableThree, row, column);
    }//GEN-LAST:event_tableThreeMouseClicked

    private void submitButtonOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonOneMouseClicked
        // TODO add your handling code here:
       calculateWeight(tableOne,"compute",tableOneResultLabel);
    }//GEN-LAST:event_submitButtonOneMouseClicked

    private void verifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifyButtonMouseClicked
        // TODO add your handling code here:
        calculateWeight(tableThree,"validate",finalTableResultLabel);
    }//GEN-LAST:event_verifyButtonMouseClicked

    private void submitButtonTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonTwoMouseClicked
        // TODO add your handling code here:
        calculateWeight(tableTwo,"compute",tableTwoResultLabel);
    }//GEN-LAST:event_submitButtonTwoMouseClicked

    /*
    *Function for getting input from jtable and feeding into ArrayList
    *Uses # and .
    */
    public ArrayList getTableData(JTable table) {
    DefaultTableModel dtm = (DefaultTableModel) table.getModel();
    int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
    ArrayList tdata = new ArrayList();
 
    for (int i = 0 ; i < nRow ; i++)
        for (int j = 0 ; j < nCol ; j++)
            if(dtm.getValueAt(i,j).equals("#")){
                tdata.add(1);
            }else{
                tdata.add(-1);
            }
    return tdata;
    }
    
    /*
    *Function for changing cell value on click
    */
    
    public void changeCellValue(JTable table,int row,int column){
        //Set from # to .    
        String value = table.getValueAt(row,column).toString();
        
        if("#".equals(value)){
            table.setValueAt(".",row,column);
        }else{
            table.setValueAt("#",row,column);
        }
    }
    
    public void calculateWeight(JTable table,String func,JLabel resultLabelName){
        ArrayList sth = getTableData(table);
        
        KiloClass kilo = new KiloClass();
        if(func == "compute"){
          kilo.compute(sth,true);
          resultLabelName.setText(KiloClass.arrayListName.toString());
          //showMessageDialog(null,KiloClass.arrayListName.toString());
        }else{
            int weight = kilo.validate(sth);
            resultLabelName.setText("Weight ="+weight);
            //showMessageDialog(null,"Weight ="+weight);
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalTableResultLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton submitButtonOne;
    private javax.swing.JButton submitButtonTwo;
    private javax.swing.JTable tableOne;
    private javax.swing.JLabel tableOneResultLabel;
    private javax.swing.JTable tableThree;
    private javax.swing.JTable tableTwo;
    private javax.swing.JLabel tableTwoResultLabel;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
